service: sagemaker-mlops-inference

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    S3_BUCKET: sagemaker-mlops-495811053995
    MODEL_BUCKET: sagemaker-mlops-495811053995
    MODEL_KEY: sagemaker-artifacts/models/xgbregressor/local-20260623100439.tar.gz

functions:
  inference:
    handler: lambda_handler.lambda_handler
    memorySize: 3008
    timeout: 900
    environment:
      MODEL_BUCKET: sagemaker-mlops-495811053995
      MODEL_KEY: sagemaker-artifacts/models/xgbregressor/local-20260623100439.tar.gz
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource: 'arn:aws:s3:::*/*'
      - Effect: Allow
        Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
        Resource: 'arn:aws:logs:*:*:*'

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!.git/**'
